//! Asserts that `docs/validator-reference.md` is in sync with the catalog.
//!
//! When this test fails, regenerate the doc by running:
//!
//! ```text
//! cargo test --test validator_reference_doc -- --nocapture --ignored generate
//! ```

use std::fs;
use std::path::PathBuf;

use jbig2::validator::catalog::checks;
use jbig2::validator::Check;

fn doc_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("docs")
        .join("validator-reference.md")
}

fn render() -> String {
    let mut out = String::new();
    out.push_str("<!-- generated by tests/validator_reference_doc.rs; regenerate with `cargo test --test validator_reference_doc -- --ignored generate` -->\n\n");
    out.push_str("# T.88 validator reference\n\n");
    out.push_str(
        "This file enumerates every `CheckId` produced by `jbig2::validator` together with the spec passage it cites. The catalog is the source of truth; this document is regenerated from it.\n\n",
    );
    out.push_str("## How to add a new check\n\n");
    out.push_str("1. Pick the smallest spec clause that the check belongs to and add a new `struct` to the matching `src/validator/catalog/clause_*.rs` module (or create one if needed).\n");
    out.push_str("2. Implement `Check`. The `id()` must be a stable `T88-<clause>-NNN` identifier; the `cite()` must quote a verbatim passage from `vendor/T-REC-T.88-201808/spec/ITU-T_T_88__08_2018.md` (or the relevant Annex).\n");
    out.push_str("3. Add the new struct to the clause module's `pub fn checks()`.\n");
    out.push_str("4. Add a positive fixture to `tools/corpus-mint/main.rs` (under `synthetic_fixtures()`) that surfaces the new id.\n");
    out.push_str("5. Inline a `#[cfg(test)] mod tests` block beside the check with at least one positive and one negative case, mirroring `clause_7_4_2.rs`.\n");
    out.push_str("6. Run `cargo run --bin corpus-mint --features validator-corpus` and `cargo test --test validator_reference_doc -- --ignored generate` to keep this doc in sync.\n\n");
    out.push_str("## Corpus layout\n\n");
    out.push_str("`tests/validator-corpus/` holds the regression corpus. Sub-directories:\n\n");
    out.push_str("- `synthetic/<clause>-<short-name>/` — hand-crafted streams produced by `tools/corpus-mint`. Each fixture targets exactly one CheckId.\n");
    out.push_str("- `annex-h-bitflip/bucket-<severity>-<id>-<seg-type>/byte-NNNN-bit-N/` — exhaustive single-bit-flip sweep over the canonical Annex H stream.\n");
    out.push_str("- `mutated/annex-h/<schedule>/...` — deterministic, seed-driven mutation cases (bit-flip, byte-replace, dlen-perturb).\n");
    out.push_str("- `bugzilla/ghostscript-<bug-id>/` — third-party JBIG2 streams harvested from `bugs.ghostscript.com`. `expected.toml` uses `primary_check_id = \"unknown\"` until a maintainer hand-classifies the bug; the regression test only requires the validator to terminate without panicking on these fixtures.\n\n");
    out.push_str("## Catalog\n\n");
    out.push_str("| CheckId | Default severity | Spec clause | Citation |\n|---|---|---|---|\n");
    for check in catalog_checks() {
        let id = check.id();
        let cite = check.cite();
        let severity = check.severity();
        let truncated = truncate(cite.quote, 140);
        out.push_str(&format!(
            "| `{}` | {:?} | `{}` | {} |\n",
            id.as_str(),
            severity,
            cite.section,
            truncated.replace('|', "\\|"),
        ));
    }
    out.push('\n');
    out.push_str("## Lenses\n\n");
    out.push_str("| Lens | Purpose |\n|---|---|\n");
    out.push_str(
        "| `Lens::StrictT88` | Default. Reports every catalog check at its declared severity. |\n",
    );
    out.push_str("| `Lens::Jbig2decInterop` | Re-weights checks that Artifex `jbig2dec` ignores in practice. |\n");
    out.push_str("| `Lens::ItuT88Interop` | Re-weights checks that the ITU-T T.88 reference codec accepts. |\n");
    out.push_str(
        "| `Lens::ImageioInterop` | Re-weights checks that PDFBox `jbig2-imageio` ignores. |\n\n",
    );
    out.push_str("## Severity semantics\n\n");
    out.push_str("- `Error`  - strict T.88 violation; renders as `BAD(N)` in matrix cells.\n");
    out.push_str("- `Warning` - non-fatal interop concern; renders as `WARN(N)`.\n");
    out.push_str("- `Info`   - advisory note (rare); does not affect verdicts.\n");
    out
}

fn catalog_checks() -> Vec<Box<dyn Check>> {
    checks()
}

fn truncate(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_string();
    }
    let mut out: String = s.chars().take(max - 1).collect();
    out.push('…');
    out
}

#[test]
fn validator_reference_doc_is_in_sync() {
    let expected = render();
    let path = doc_path();
    let actual = fs::read_to_string(&path).unwrap_or_default();
    if actual != expected {
        panic!(
            "{} is out of sync with the catalog.\n\nRegenerate with `cargo test --test validator_reference_doc -- --ignored generate` and commit the result.",
            path.display()
        );
    }
}

#[test]
#[ignore]
fn generate() {
    let path = doc_path();
    let rendered = render();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(&path, rendered).unwrap();
    eprintln!("wrote {}", path.display());
}
